# Generated by Django 4.2.11 on 2025-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_speed_x',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_speed_y',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.CharField(default='pvp', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='last_hit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_y',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_y',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player3_x',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='game',
            name='player4_x',
            field=models.FloatField(default=400),
        ),
    ]
