# Generated by Django 3.0.14 on 2025-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20250207_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('PVB', 'Player vs Bot'), ('PVP', 'Player vs Player'), ('MP', 'Multiplayer'), ('TRN', 'Tournament Match'), ('OPVP', 'Online Player vs Player')], max_length=4),
        ),
    ]
