# Generated by Django 3.0.14 on 2025-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20250212_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='is_tournament_match',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='tournament_match_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='tournament_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
