# Generated by Django 4.2.11 on 2025-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_dx',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_dy',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='canvas_height',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='game',
            name='canvas_width',
            field=models.IntegerField(default=800),
        ),
    ]
