# Generated by Django 3.0.14 on 2025-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20250212_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='is_tournament_match',
            field=models.BooleanField(default=False),
        ),
    ]
