# Generated by Django 3.0.14 on 2025-02-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameresult_is_tournament_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='tournament_match_order',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='tournament_stage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
