# Generated by Django 3.0.14 on 2025-02-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_gameresult_tournament_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='player3_score',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='player4_score',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('PVP', 'Player vs Player'), ('TRN', 'Tournament Match'), ('OPVP', 'Online Player vs Player')], max_length=4),
        ),
    ]
