# Generated by Django 3.0.14 on 2025-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20250213_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('PVP', 'Player vs Player'), ('TRN', 'Tournament Match'), ('MM', 'Matchmaking')], max_length=4),
        ),
    ]
